name: Dockerfile
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    name: ubuntu-latest
    steps:
    - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # updated on Jan 16
    
    - run: docker build . --file Dockerfile
